version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/uvicorn/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    # Add command to run migrations, etc.

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    env_file:
      - .env

volumes:
  postgres_data:
